--- #YAML:1.0
name: graph-perl-usage
abstract: graph Perl Package usage
version: 0.05
version_from: gen_graph
license: gpl
distribution_type: module
generated_by: graph-perl-usage version 0.05
installdirs: site
requires:
  Graph::Easy: 0.27
